// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Page struct {
	ID            int64          `json:"id"`
	Url           string         `json:"url"`
	SourceSitemap sql.NullString `json:"source_sitemap"`
	Lastmod       sql.NullString `json:"lastmod"`
	ScrapeStatus  string         `json:"scrape_status"`
	StatusCode    sql.NullInt64  `json:"status_code"`
	DurationMs    sql.NullInt64  `json:"duration_ms"`
	Error         sql.NullString `json:"error"`
	VisitedAt     sql.NullString `json:"visited_at"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type Sitemap struct {
	ID             int64          `json:"id"`
	Url            string         `json:"url"`
	DiscoveredFrom string         `json:"discovered_from"`
	Status         string         `json:"status"`
	Type           sql.NullString `json:"type"`
	Error          sql.NullString `json:"error"`
	DelayMs        int64          `json:"delay_ms"`
	DurationMs     int64          `json:"duration_ms"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type StructuredProduct struct {
	ID        int64  `json:"id"`
	PageID    int64  `json:"page_id"`
	RawJson   string `json:"raw_json"`
	ScrapedAt string `json:"scraped_at"`
}
