// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countPages = `-- name: CountPages :one
SELECT COUNT(*) FROM pages
`

func (q *Queries) CountPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingPages = `-- name: CountPendingPages :one
SELECT COUNT(*) FROM pages WHERE visited_at IS NULL
`

func (q *Queries) CountPendingPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStructuredProducts = `-- name: CountStructuredProducts :one
SELECT COUNT(*) FROM structured_products
`

func (q *Queries) CountStructuredProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStructuredProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPageByURL = `-- name: GetPageByURL :one
SELECT id, url, source_sitemap, lastmod, scrape_status, status_code, duration_ms, error, visited_at, created_at, updated_at
FROM pages
WHERE url = ?1
`

func (q *Queries) GetPageByURL(ctx context.Context, url string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageByURL, url)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.SourceSitemap,
		&i.Lastmod,
		&i.ScrapeStatus,
		&i.StatusCode,
		&i.DurationMs,
		&i.Error,
		&i.VisitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStructuredProduct = `-- name: InsertStructuredProduct :exec
INSERT INTO structured_products (
  page_id,
  raw_json
) VALUES (
  ?1,
  ?2
)
`

type InsertStructuredProductParams struct {
	PageID  int64  `json:"page_id"`
	RawJson string `json:"raw_json"`
}

func (q *Queries) InsertStructuredProduct(ctx context.Context, arg InsertStructuredProductParams) error {
	_, err := q.db.ExecContext(ctx, insertStructuredProduct, arg.PageID, arg.RawJson)
	return err
}

const listAllPendingPages = `-- name: ListAllPendingPages :many
SELECT id, url, source_sitemap, lastmod, scrape_status, status_code, duration_ms, error, visited_at, created_at, updated_at
FROM pages
WHERE visited_at IS NULL
ORDER BY id
`

func (q *Queries) ListAllPendingPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listAllPendingPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.SourceSitemap,
			&i.Lastmod,
			&i.ScrapeStatus,
			&i.StatusCode,
			&i.DurationMs,
			&i.Error,
			&i.VisitedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPages = `-- name: ListPendingPages :many
SELECT id, url, source_sitemap, lastmod, scrape_status, status_code, duration_ms, error, visited_at, created_at, updated_at
FROM pages
WHERE visited_at IS NULL
ORDER BY id
LIMIT ?1 OFFSET ?2
`

type ListPendingPagesParams struct {
	LimitCount  int64
	OffsetCount int64
}

func (q *Queries) ListPendingPages(ctx context.Context, arg ListPendingPagesParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPages, arg.LimitCount, arg.OffsetCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.SourceSitemap,
			&i.Lastmod,
			&i.ScrapeStatus,
			&i.StatusCode,
			&i.DurationMs,
			&i.Error,
			&i.VisitedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPageFailure = `-- name: MarkPageFailure :exec
UPDATE pages
SET scrape_status = 'failed',
  status_code = ?1,
  duration_ms = ?2,
  error = ?3,
  visited_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP
WHERE url = ?4
`

type MarkPageFailureParams struct {
	StatusCode sql.NullInt64  `json:"status_code"`
	DurationMs sql.NullInt64  `json:"duration_ms"`
	Error      sql.NullString `json:"error"`
	Url        string         `json:"url"`
}

func (q *Queries) MarkPageFailure(ctx context.Context, arg MarkPageFailureParams) error {
	_, err := q.db.ExecContext(ctx, markPageFailure,
		arg.StatusCode,
		arg.DurationMs,
		arg.Error,
		arg.Url,
	)
	return err
}

const markPageSuccess = `-- name: MarkPageSuccess :exec
UPDATE pages
SET scrape_status = 'success',
  status_code = ?1,
  duration_ms = ?2,
  error = NULL,
  visited_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP
WHERE url = ?3
`

type MarkPageSuccessParams struct {
	StatusCode sql.NullInt64 `json:"status_code"`
	DurationMs sql.NullInt64 `json:"duration_ms"`
	Url        string        `json:"url"`
}

func (q *Queries) MarkPageSuccess(ctx context.Context, arg MarkPageSuccessParams) error {
	_, err := q.db.ExecContext(ctx, markPageSuccess, arg.StatusCode, arg.DurationMs, arg.Url)
	return err
}

const upsertPage = `-- name: UpsertPage :exec
INSERT INTO pages (
  url,
  source_sitemap,
  lastmod
) VALUES (
  ?1,
  ?2,
  ?3
)
ON CONFLICT(url) DO UPDATE SET
  source_sitemap = excluded.source_sitemap,
  lastmod = COALESCE(excluded.lastmod, pages.lastmod),
  updated_at = CURRENT_TIMESTAMP
`

type UpsertPageParams struct {
	Url           string         `json:"url"`
	SourceSitemap sql.NullString `json:"source_sitemap"`
	Lastmod       sql.NullString `json:"lastmod"`
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertPage, arg.Url, arg.SourceSitemap, arg.Lastmod)
	return err
}

const upsertSitemap = `-- name: UpsertSitemap :exec
INSERT INTO sitemaps (
  url,
  discovered_from,
  status,
  type,
  error,
  delay_ms,
  duration_ms
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7
)
ON CONFLICT(url) DO UPDATE SET
  discovered_from = excluded.discovered_from,
  status = excluded.status,
  type = excluded.type,
  error = excluded.error,
  delay_ms = excluded.delay_ms,
  duration_ms = excluded.duration_ms,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertSitemapParams struct {
	Url            string         `json:"url"`
	DiscoveredFrom string         `json:"discovered_from"`
	Status         string         `json:"status"`
	Type           sql.NullString `json:"type"`
	Error          sql.NullString `json:"error"`
	DelayMs        int64          `json:"delay_ms"`
	DurationMs     int64          `json:"duration_ms"`
}

func (q *Queries) UpsertSitemap(ctx context.Context, arg UpsertSitemapParams) error {
	_, err := q.db.ExecContext(ctx, upsertSitemap,
		arg.Url,
		arg.DiscoveredFrom,
		arg.Status,
		arg.Type,
		arg.Error,
		arg.DelayMs,
		arg.DurationMs,
	)
	return err
}
